data:
    dataset: "ImageNet"
    image_size: 256
    channels: 3                          #todo
    logit_transform: false
    uniform_dequantization: false
    gaussian_dequantization: false
    random_flip: true
    rescaled: true
    num_workers: 12
    subset_1k: True
    out_of_dist: False

model:
    name: "model000000.pt"           # model006000.pt for "DRUS/WDRUS"(picmus), model000000.pt for "HtH/CHtH"(synthetic)
    problem_model: "CHtH"            # select from [ "DRUS" || "WDRUS" || "HtH" || "CHtH" ]
    in_channels: 3                   # todo
    out_channels: 1
    num_channels: 256 #192
    num_heads: 4
    num_res_blocks: 2
    attention_resolutions: "32,16,8"
    dropout: 0.0
    resamp_with_conv: True
    learn_sigma: True
    use_scale_shift_norm: true
    use_fp16: true
    resblock_updown: true
    num_heads_upsample: -1
    var_type: 'fixedsmall'
    num_head_channels: 64
    image_size: 256
    class_cond: false
    use_new_attention_order: false

diffusion:
    beta_schedule: linear
    beta_start: 0.0001
    beta_end: 0.02
    num_diffusion_timesteps: 1000

sampling:
    batch_size: 1
    last_only: True
